-- run via:
-- :PlenaryBustedFile tests/dates_spec.lua

local dates = require("zettlekast.dates")

describe("dates", function()
    describe("today", function()
        it("should return a YYYY-MM-DD string", function()
            local result = dates.today()
            assert.is_truthy(result:match("^%d%d%d%d%-%d%d%-%d%d$"))
        end)
    end)

    describe("daily_filename", function()
        it("should return YYYY-MM-DD.md", function()
            local result = dates.daily_filename()
            assert.is_truthy(result:match("^%d%d%d%d%-%d%d%-%d%d%.md$"))
        end)
    end)

    describe("weekly_filename", function()
        it("should return YYYY-WNN.md", function()
            local result = dates.weekly_filename()
            assert.is_truthy(result:match("^%d%d%d%d%-W%d%d%.md$"))
        end)
    end)

    describe("is_daily", function()
        it("should match daily note filenames", function()
            assert.is_true(dates.is_daily("2026-02-15.md"))
            assert.is_true(dates.is_daily("2025-01-01.md"))
        end)

        it("should not match non-daily filenames", function()
            assert.is_false(dates.is_daily("my-note.md"))
            assert.is_false(dates.is_daily("2026-W05.md"))
        end)
    end)

    describe("is_weekly", function()
        it("should match weekly note filenames", function()
            assert.is_true(dates.is_weekly("2026-W05.md"))
            assert.is_true(dates.is_weekly("2025-W52.md"))
        end)

        it("should not match non-weekly filenames", function()
            assert.is_false(dates.is_weekly("2026-02-15.md"))
            assert.is_false(dates.is_weekly("my-note.md"))
        end)
    end)

    describe("parse_date", function()
        it("should parse a YYYY-MM-DD string", function()
            local result = dates.parse_date("2026-02-15")
            assert.is_not_nil(result)
        end)

        it("should return nil for invalid date strings", function()
            assert.is_nil(dates.parse_date("not-a-date"))
            assert.is_nil(dates.parse_date("2026/02/15"))
        end)
    end)

    describe("generate_uuid", function()
        it("should generate a uuid string", function()
            local result = dates.generate_uuid("%Y-%m-%d-%H%M")
            assert.is_truthy(result:match("^%d%d%d%d%-%d%d%-%d%d%-%d%d%d%d$"))
        end)
    end)

    describe("template_vars", function()
        it("should return a table with date fields", function()
            local vars = dates.template_vars()
            assert.is_not_nil(vars.date)
            assert.is_not_nil(vars.time)
            assert.is_not_nil(vars.year)
            assert.is_not_nil(vars.month)
            assert.is_not_nil(vars.day)
            assert.is_not_nil(vars.hdate)
            assert.is_not_nil(vars.week)
        end)
    end)
end)
